; Options & Styles

[Variables]
BGImagePath=#@#/#Theme#/null.png
Blur=0
GlassColorInt=180
GlassGlowShadowInt=200
GlassNoFrames=0
InfobarColor=0,0,0
Theme=Red
LostSetTime=108
LostTerminalInput=0
LostCurTime=37
LostFailureTime=1
LostLockdown=0

[VLine]
ScaleMargins=0,1,0,2
ImageName=#@#/#Theme#/v-divider.png
W=3

[HLine]
ScaleMargins=1,0,2,0
ImageName=#@#/#Theme#/h-divider.png
H=3

[TextBox]
SolidColor=0,0,0,1
ScaleMargins=4,4,4,4
ImageName=#@#/#Theme#/text.png
